global:
  scrape_interval: 5s
  evaluation_interval: 5s

  external_labels:
    cluster: 'Rich-Prometheus'

###################################################
#### SCRAPE CONFIGS
###################################################
scrape_configs:
  ###################################################
  #### Prometheus
  ###################################################
  - job_name: 'rich-prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'rich'
    static_configs:
      - targets: ['host.docker.internal:5580']